include:
  - board: xiao_rp2040//zmk
    shield: totem_left
    cmake-args: -DZMK_EXTRA_MODULES=${GITHUB_WORKSPACE}/totem-module
  - board: xiao_rp2040//zmk
    shield: totem_right
    cmake-args: -DZMK_EXTRA_MODULES=${GITHUB_WORKSPACE}/totem-module
# there is no settingsreset (needed) for the XIAO
