parse_config:
  zmk_additional_includes:
    - "modules/zmk/helpers/include"

  zmk_preamble: |
    #include <zmk-helpers/key-labels/totem.h>

  raw_binding_map:
    "&studio_unlock": Unlock
    "&sys_reset": Reset
    "&bootloader": Boot
    "&caps_word": Caps Word

    "&kp LC(INS)": Copy
    "&kp LC(X)": Cut
    "&kp LS(INS)": Paste

    "&kp LG(LC(LEFT))": Prev Desk
    "&kp LG(LC(RIGHT))": Next Desk
    "&kp LG(LC(LS(A)))": Pin App
    "&kp LG(LC(LS(Q)))": Pin Win

    "&swapper": Next Win
    "&kp LS(TAB)": Prev Win
    "&dot_spc": Sentence
    "&num_dance": { "t": "Numword", "s": "Sticky Num" }
    "&magic_shift": { "t": Magic, "h": "Shift" }
    "&smart_mouse": Smart Mouse

    "&hml LS(LALT)TAB": Tab
    "&hm_combo_ldr": Leader
    "&hm_combo_ldrsh": Shift+Leader
    "&hm_combo_lpar": { "t": "(", "right": "<" }
    "&hm_combo_rpar": { "t": ")", "right": ">" }
    "&kp LBKT": { "t": "[", "right": "{" }
    "&kp RBKT": { "t": "]", "right": "}" }

    "&mmv MOVE_UP": Mouse ↑
    "&mmv MOVE_DOWN": Mouse ↓
    "&mmv MOVE_LEFT": Mouse ←
    "&mmv MOVE_RIGHT": Mouse →

    "&msc SCRL_UP": Scroll ↑
    "&msc SCRL_DOWN": Scroll ↓
    "&msc SCRL_LEFT": Scroll ←
    "&msc SCRL_RIGHT": Scroll →

    "&mkp LCLK": Left Click
    "&mkp RCLK": Right Click
    "&mkp MCLK": Middle Click

  trans_legend: { "t": "", "type": "trans" }

  zmk_combos:
    combo_cut: { align: bottom, o: 0.15 }
    combo_ldrsh: { align: top, o: 1.35 }

    combo_lt: { hidden: true }
    combo_gt: { hidden: true }
    combo_lbrc: { hidden: true }
    combo_rbrc: { hidden: true }

  zmk_keycode_map:
    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LGUI: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    PG_UP: $$mdi:transfer-up$$
    PG_DN: $$mdi:transfer-down$$

    # Whitespace
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

    # Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$

    # System
    C_POWER: $$mdi:power-standby$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL: $$mdi:close-box$$

    INS: Ins
    HOME: Home
    END: End

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    AMPERSAND: "&"
    AMPS: "&"
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: "*"
    ASTRK: "*"
    AT: "@"
    AT_SIGN: "@"
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ":"
    COMMA: ","
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: "="
    EXCL: "!"
    EXCLAMATION: "!"
    FSLH: /
    GRAVE: "`"
    GREATER_THAN: ">"
    GT: ">"
    HASH: "#"
    LBKT: "["
    LBRC: "{"
    LEFT_BRACE: "{"
    LEFT_BRACKET: "["
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: "-"
    NON_US_BACKSLASH: \
    NON_US_BSLH: "|"
    NON_US_HASH: "#"
    NUHS: "#"
    PERCENT: "%"
    PERIOD: .
    PIPE: "|"
    PIPE2: "|"
    PLUS: +
    POUND: "#"
    PRCNT: "%"
    QMARK: "?"
    QUESTION: "?"
    RBKT: "]"
    RBRC: "}"
    RIGHT_BRACE: "}"
    RIGHT_BRACKET: "]"
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: "'"
    SLASH: /
    SQT: "'"
    STAR: "*"
    TILDE: "~"
    TILDE2: "~"
    UNDER: _
    UNDERSCORE: _

draw_config:
  dark_mode: true
  svg_style: |
    /* force mdi glyph defs to inherit color from glyph references */
    svg path {
        fill: inherit;
    }

    defs svg {
        overflow: visible;
    }

    defs svg path {
        fill: currentColor;
    }

    svg.keymap {
        font-family: REM, "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
        font-size: 14px;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
        fill: rgb(38, 50, 56);
    }

    rect.key {
        fill: rgb(236, 239, 241);
    }

    rect.key, rect.combo {
        stroke: white;
        stroke-width: 1;
    }

    .keypos-10 rect.key,
    .keypos-19 rect.key,
    .keypos-30 rect.key,
    .keypos-37 rect.key {
        fill: rgb(207, 216, 220);
    }

    .keypos-10 rect.key,
    .keypos-19 rect.key {
        stroke: rgb(236, 239, 241);
    }

    .keypos-12 rect.key,
    .keypos-16 rect.key,
    .keypos-31 rect.key,
    .keypos-36 rect.key {
        fill: rgb(229, 115, 115);
        stroke: rgb(239, 154, 154);
    }

    .keypos-11 rect.key,
    .keypos-18 rect.key,
    .keypos-32 rect.key,
    .keypos-35 rect.key {
        fill: rgb(128, 203, 196);
        stroke: rgb(178, 223, 219);
    }

    .keypos-30 text,
    .keypos-31 text,
    .keypos-32 text,
    .keypos-35 text,
    .keypos-36 text,
    .keypos-37 text {
        fill: rgb(38, 50, 56);
    }

    rect.side {
        filter: brightness(90%);
    }

    rect.combo, rect.combo-separate {
        fill: rgb(207, 216, 220);
    }

    rect.held, rect.combo.held {
        fill: rgb(229, 115, 115);
    }

    rect.ghost, rect.combo.ghost {
        stroke-dasharray: 4, 4;
        stroke-width: 2;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
    }

    text.label {
        font-weight: bold;
        text-anchor: start;
        fill: rgb(120, 144, 156);
        stroke: white;
        stroke-width: 4;
        paint-order: stroke;
    }

    text.footer {
        text-anchor: end;
        dominant-baseline: auto;
        stroke: white;
        stroke-width: 4;
        paint-order: stroke;
    }

    text.combo, text.hold, text.shifted, text.left, text.right, text.tl, text.tr, text.bl, text.br {
        font-size: 11px;
    }

    text.hold, text.shifted, text.left, text.right, text.tl, text.tr, text.bl, text.br {
        fill: rgb(96, 125, 139);
    }

    text.hold, text.bl, text.br {
        text-anchor: middle;
        dominant-baseline: auto;
    }

    text.shifted, text.tl, text.tr {
        text-anchor: middle;
        dominant-baseline: hanging;
    }

    text.left, text.tl, text.bl {
        text-anchor: start;
    }

    text.right, text.tr, text.br {
        text-anchor: end;
    }

    text.layer-activator {
        text-decoration: underline;
        fill: rgb(38, 50, 56);
    }

    text.combo.hold, text.combo.shifted, text.combo.left, text.combo.right {
        font-size: 8px;
    }

    text.combo.tap {
        fill: rgb(55, 71, 79);
    }

    use.glyph {
        fill: rgb(38, 50, 56);
        color: rgb(38, 50, 56);
    }

    use.combo.glyph {
        fill: rgb(55, 71, 79);
        color: rgb(55, 71, 79);
    }

    text.combo.hold, text.combo.left, text.combo.right {
        fill: rgb(55, 71, 79);
    }

    text.combo.shifted {
        fill: rgb(120, 144, 156);
    }

    text.trans {
        fill: rgb(120, 144, 156);
        opacity: 0.4;
    }

    path.combo {
        stroke-width: 1;
        stroke: rgb(207, 216, 220);
        fill: none;
    }

    .icon-tabler > path {
        fill: inherit;
        stroke: inherit;
        stroke-width: 2;
    }

    .icon-tabler > path[stroke="none"][fill="none"] {
        visibility: hidden;
    }
  svg_style_dark: |
    svg.keymap { fill: rgb(38, 50, 56); }
    rect.key { fill: rgb(236, 239, 241); }
    rect.key, rect.combo { stroke: white; }
    rect.combo, rect.combo-separate { fill: rgb(207, 216, 220); stroke: rgb(207, 216, 220); }
    rect.held, rect.combo.held { fill: rgb(229, 115, 115); }
    text.label, text.footer { stroke: white; }
    text.trans { fill: rgb(120, 144, 156); opacity: 0.4; }
    path.combo { stroke: rgb(207, 216, 220); }
